version: '3'
services:
  eureka:
    image: eureka
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    tty: true
    restart: on-failure
    container_name: eureka
    networks:
      - rent-a-car-network

  zuul:
    image: zuul
    build:
      context: ./Zuul
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    tty: true
    restart: on-failure
    container_name: zuul
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - rent-a-car-network


  adservice:
    image: adservice
    build:
      context: ./AdService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    tty: true
    restart: on-failure
    container_name: adservice
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - rent-a-car-network


  authenticationservice:
    image: authenticationservice
    build:
      context: ./AuthenticationService
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    tty: true
    restart: on-failure
    container_name: authenticationservice
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - rent-a-car-network


  chatservice:
    image: chatservice
    build:
      context: ./ChatService
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    tty: true
    restart: on-failure
    container_name: chatservice
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - rent-a-car-network


  rentrequestservice:
    image: rentrequestservice
    build:
      context: ./RentRequestService
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    tty: true
    restart: on-failure
    container_name: rentrequestservice
    depends_on:
      - eureka
    environment:
      - REGISTRY_HOST=eureka
    networks:
      - rent-a-car-network

  reviewservice:
    image: reviewservice
    build:
      context: ./ReviewService
      dockerfile: Dockerfile
    ports:
        - "8092:8092"
    tty: true
    restart: on-failure
    container_name: reviewservice
    depends_on:
        - eureka
    environment:
        - REGISTRY_HOST=eureka
    networks:
        - rent-a-car-network

networks:
  rent-a-car-network:
    driver: bridge
