version: '3'
services:
  eureka:
    image: eureka
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - rent-a-car-network

  zuul:
    image: zuul
    build:
      context: ./Zuul
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  administrationservice:
    image: administrationservice
    build:
      context: ./AdministrationService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  adservice:
    image: adservice
    build:
      context: ./AdService
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  authenticationservice:
    image: authenticationservice
    build:
      context: ./AuthenticationService
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  chatservice:
    image: chatservice
    build:
      context: ./ChatService
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  pricelistservice:
    image: pricelistservice
    build:
      context: ./PricelistService
      dockerfile: Dockerfile
    ports:
      - "8077:8077"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  rentrequestservice:
    image: rentrequestservice
    build:
      context: ./RentRequestService
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    links:
      - eureka
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
      - rent-a-car-network

  reportservice:
    image: reportservice
    build:
      context: ./ReportService
      dockerfile: Dockerfile
    ports:
        - "8091:8091"
    links:
        - eureka
    depends_on:
        - eureka
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
        - rent-a-car-network


  reviewservice:
    image: reviewservice
    build:
      context: ./ReviewService
      dockerfile: Dockerfile
    ports:
        - "8092:8092"
    links:
        - eureka
    depends_on:
        - eureka
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
        - rent-a-car-network

  userservice:
    image: userservice
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
        - "8056:8056"
    links:
        - eureka
    depends_on:
        - eureka
    environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    networks:
        - rent-a-car-network

networks:
  rent-a-car-network:
    driver: bridge

